CREATE DATABASE IF NOT EXISTS librarydb;
USE librarydb;
CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    author VARCHAR(255),
    issued TINYINT(1) DEFAULT 0
);
